### ISSUE TITLE
Expose reason for failure of opening Ant+ stick

### ISSUE THREAD

**Issue by Abasz** [incyclist/ant-plus#32]
Hi, thanks for this library, it works great.

However we encountered currently your library only exposes the fact whether it was able to connect to an ant+ stick or not (via boolean return type of the `open()` method):

https://github.com/incyclist/ant-plus/blob/070fea6b46f7478de3deae4bc9a31a2803436831/src/ant-device.ts#L95

When it returns false (i.e. was not able to connect) this does not allow the caller to understand what was the reason for the failure (e.g. no stick is connected, or its already in use, lost connection etc.) and in our code we cannot act appropriately (e.g. throw an error if no stick is found, but log to the console if already in use).

Would it be possible to return an object that includes details on the reason behind connection failure. Or an enum , like `Success, AlreadyInUse, NoStick, CommunicationError, StartupError` or any other more descriptive return value? 

I can see that in the core there are 3 cases when false is returned and all seemed to have different reason, so technically this is possible, but I understand that it would be a breaking change.

**Comment by gdoumen** [comment]
As already indicated, changing the result from Boolean to something else (enum or Error), would be a breaking change. 

I would see two options to address this: 

1)  I could add a property in the `AntDeviceProps` provided in the constructor of the AntDevice class. Here I could add a property `detailedStartReport?:boolean`, which would default to false

Only if this propery would be set, I would return the DetailedStarte Result ( Success vs. NoStick vs ....)

2) I could emit an event of a Start Failure containing the details of the failure

3) I could add an optional ErrorCallback as argument of the Open function.

I personally would find #1 the easiest to consume

**Comment by gdoumen** [comment]
@Abasz  the feature has been implemented in version 0.2.0 of the library
